수업자료/database/03-02-many-to-many-relationships/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

수업자료/database/03-02-many-to-many-relationships/articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:article_pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:article_pk>/likes/', views.likes, name='likes'),
]

수업자료/database/03-02-many-to-many-relationships/crud/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('<int:user_pk>/password/', views.change_password, name="change_password"),
]

수업자료/database/03-02-many-to-many-relationships/articles/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Article(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    """
    M:N관계 설정 시 그냥 복수형으로 이름을 짓는 것 보다,
    지금 우리가 만드는 기능이 무엇인지 생각해보고 명시적인 매니저 이름을 설정하는 것이 좋다.
    
    게시글 1번에 좋아요를 누른 모든 유저 조회
    (Article -> User / 참조)

    `게시글1.users.all()` 표현을 다음과 같이 표현하는 것이 더 적합하다. 
    `게시글1.like_users.all()`
    """
    """
    [역참조 매니저 이름 충돌 상황]
    - Article : User (N:1)
        - article.user (참조)
        - user.article_set (역참조)
    - Article : User (N:M)
        - article.like_users (참조)
        - user.article_set  (역참조)
        - user.like_articles (새로운 역참조 이름으로 변경)
    - N:1 관계의 역참조 이름(_set)은 바꾸지 않는 것을 권장한다.
        - 개발 시 _set 이름만 봤을 때 "아 지금  N:1에서 역참조를 하는것이구나"를 명시적으로 알기 위함이다.
    """
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

수업자료/database/03-02-many-to-many-relationships/articles/forms.py
from django import forms
from .models import Article, Comment


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ('title', 'content',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

수업자료/database/03-02-many-to-many-relationships/articles/views.py
from django.shortcuts import redirect, render
from .forms import ArticleForm, CommentForm
from .models import Article, Comment


def index(request):
    articles = Article.objects.all()
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)


def detail(request, pk):
    article = Article.objects.get(pk=pk)
    comment_form = CommentForm()
    comments = article.comment_set.all()
    context = {
        'article': article,
        'comment_form': comment_form,
        'comments': comments,
    }
    return render(request, 'articles/detail.html', context)


def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm()
    context = {
        'form': form,
    }
    return render(request, 'articles/create.html', context)


def delete(request, pk):
    article = Article.objects.get(pk=pk)
    if request.user == article.user:
        article.delete()
    return redirect('articles:index')


def update(request, pk):
    article = Article.objects.get(pk=pk)
    if request.user == article.user:
        if request.method == 'POST':
            form = ArticleForm(request.POST, instance=article)
            if form.is_valid():
                form.save()
                return redirect('articles:detail', article.pk)
        else:
            form = ArticleForm(instance=article)
    else:
        return redirect('articles:index')
    context = {
        'article': article,
        'form': form,
    }
    return render(request, 'articles/update.html', context)


def comments_create(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.article = article
        comment.user = request.user
        comment.save()
        return redirect('articles:detail', article.pk)
    context = {
        'comment_form': comment_form,
    }
    return render(request, 'articles/detail.html', context)


def comments_delete(request, article_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.user == comment.user:
        comment.delete()
    return redirect('articles:detail', article_pk)


def likes(request, article_pk):
    # 좋아요를 누를 게시글이 어떤건지 조회
    article = Article.objects.get(pk=article_pk)

    # 좋아요 추가 / 좋아요 취소
    # 언제 추가하고 언제 취소할지 어떻게 구별할 것인지?
    # 좋아요를 요청하는 주체는 request.user
    # request.user가 지금 특정 게시글에 좋아요를 누른 유저 목록에 있다면? 없다면?을 확인

    # 만약 특정 게시글에 좋아요를 누른 유저 목록에 현재 요청하는 유저가 있다면? -> 취소
    if request.user in article.like_users.all():
        article.like_users.remove(request.user)
        # request.user.like_articles.remove(article)
    else:
        article.like_users.add(request.user)
        # request.user.like_articles.add(article)
    return redirect('articles:index')

수업자료/database/03-02-many-to-many-relationships/articles/templates/articles/create.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>CREATE</h1>
  <form action="{% url "articles:create" %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
  <hr>
  <a href="{% url "articles:index" %}">[back]</a>
</body>
</html>

수업자료/database/03-02-many-to-many-relationships/articles/templates/articles/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>DETAIL</h1>
  <h2>{{ article.pk }} 번째 글</h2>
  <hr>
  <p>작성자 : {{ article.user }}</p>
  <p>제목 : {{ article.title }}</p>
  <p>내용 : {{ article.content }}</p>
  <p>작성일 : {{ article.created_at }}</p>
  <p>수정일 : {{ article.updated_at }}</p>
  <hr>
  {% if request.user == article.user %}
    <a href="{% url "articles:update" article.pk %}">[UPDATE]</a>
    <form action="{% url "articles:delete" article.pk %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="삭제">
    </form>
  {% endif %}
  <hr>
  {% comment %} 댓글 작성 Form {% endcomment %}
  <form action="{% url "articles:comments_create" article.pk  %}" method="POST">
    {% csrf_token %}
    {{ comment_form }}
    <input type="submit">
  </form>
  <hr>
  {% comment %} 댓글 목록 {% endcomment %}
  <h2>댓글 목록</h2>
  <ul>
    {% for comment in comments %}
      <li>
        {{ comment.user }} - {{ comment.content }}
        {% if request.user == comment.user %}
          <form action="{% url "articles:comments_delete" article.pk comment.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="삭제">
          </form>
        {% endif %}
      </li>
    {% endfor %}
  </ul>
  <a href="{% url "articles:index" %}">[back]</a>
</body>
</html>

수업자료/database/03-02-many-to-many-relationships/articles/templates/articles/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Articles</h1>
  {% comment %} {% if user.is_authenticated %} {% endcomment %}
  {% if request.user.is_authenticated %}
    <h1>안녕하세요, {{ user.username }}님</h1>
    <a href="{% url "accounts:profile" user.username %}">내 프로필</a>
    <a href="{% url "articles:create" %}">CREATE</a>
    <form action="{% url "accounts:logout" %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="로그아웃">
    </form>
    <form action="{% url "accounts:delete" %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="회원탈퇴">
    </form>
    <a href="{% url "accounts:update" %}">회원정보 수정</a>
  {% else %}
    <a href="{% url "accounts:login" %}">로그인</a>
    <a href="{% url "accounts:signup" %}">회원가입</a>
  {% endif %}

  <hr>

  {% for article in articles %}
    <p>
      작성자 : 
      <a href="{% url "accounts:profile" article.user.username %}">{{ article.user }}</a>
    </p>
    {% comment %} <p>작성자 : {{ article.user.username }}</p> {% endcomment %}
    <p>글 번호: {{ article.pk }}</p>
    <a href="{% url "articles:detail" article.pk %}">
      <p>글 제목: {{ article.title }}</p>
    </a>
    <p>글 내용: {{ article.content }}</p>
    {% comment %} 좋아요 버튼 {% endcomment %}
    <form action="{% url "articles:likes" article.pk %}" method="POST">
      {% csrf_token %}
      {% if request.user in article.like_users.all %}
        <input type="submit" value="좋아요 취소">
      {% else %}
        <input type="submit" value="좋아요">
      {% endif %}
    </form>
    <hr>
  {% endfor %}
</body>
</html>

수업자료/database/03-02-many-to-many-relationships/articles/templates/articles/update.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>UPDATE</h1>
  <form action="{% url "articles:update" article.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
  <hr>
  <a href="{% url "articles:detail" article.pk %}">[back]</a>
</body>
</html>