수업자료/django/02-template-urls/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('dinner/', views.dinner, name='dinner'),
    path('search/', views.search, name='search'),
    path('throw/', views.throw, name='throw'),
    path('catch/', views.catch, name='catch'),
    path('<int:num>/', views.detail, name='detail'),
]

수업자료/django/02-template-urls/firstpjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    # path('pages/', include('pages.urls')),
]

수업자료/django/02-template-urls/pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'
urlpatterns = [
    path('', views.index, name='index'),
]

수업자료/django/02-template-urls/articles/views.py
import random
from django.shortcuts import render


# Create your views here.
def index(request):
    context = {
        'name': 'SSAFY',
    }
    return render(request, 'articles/index.html', context)


def dinner(request):
    foods = ['국밥', '국수', '카레', '탕수육',]
    picked = random.choice(foods)
    context = {
        'foods': foods,
        'picked': picked,
    }
    return render(request, 'articles/dinner.html', context)


def search(request):
    return render(request, 'articles/search.html')


def throw(request):
    return render(request, 'articles/throw.html')


def catch(request):
    # print(request)  # <WSGIRequest: GET '/catch/?message=ssafy'>
    # print(type(request))  # <class 'django.core.handlers.wsgi.WSGIRequest'>
    # print(request.GET)  # <QueryDict: {'message': ['ssafy']}>
    # print(request.GET.get('message'))  # ssafy
    message = request.GET.get('message')
    context = {
        'message': message,
    }
    return render(request, 'articles/catch.html', context)


def detail(request, num):
    context = {
        'num': num,
    }
    return render(request, 'articles/detail.html', context)

수업자료/django/02-template-urls/pages/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'pages/index.html')

수업자료/django/02-template-urls/articles/templates/articles/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% block style %}
    {% endblock style %}
  </head>
  <body>
    {% block content %}
    {% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

수업자료/django/02-template-urls/articles/templates/articles/catch.html
{% extends "articles/base.html" %}

{% block content %}
  <h1>Catch</h1>
  <h2>{{ message }}를 받았습니다.</h2>
{% endblock content %}

수업자료/django/02-template-urls/articles/templates/articles/detail.html
{% extends "articles/base.html" %}

{% block content %}
  <h1>Detail</h1>
  <h2>{{ num }}번 게시글입니다.</h2>
{% endblock content %}

수업자료/django/02-template-urls/articles/templates/articles/dinner.html
{% extends "articles/base.html" %}

{% block content %}
  <p>{{ picked }} 메뉴는 {{ picked|length }}글자 입니다.</p>
  <h2>메뉴판</h2>
  <ul>
    {% for food in foods %}
      <li>{{ food }}</li>
    {% endfor %}
  </ul>
  {% if picked|length == 0 %}
    <p>메뉴가 소진 되었습니다.</p>
  {% else %}
    <p>아직 메뉴가 남았습니다.</p>
  {% endif %}
{% endblock content %}

수업자료/django/02-template-urls/articles/templates/articles/index.html
{% extends "articles/base.html" %}

{% block style %}
<style>
  h1 {
    color: crimson;
  }
</style>
{% endblock style %}

{% block content %}
  <h1>Hello, {{ name }}</h1>
  <a href="{% url "articles:dinner" %}"></a>
  <a href="{% url "articles:search" %}"></a>
  <a href="{% url "articles:dinner" %}"></a>
  <a href="{% url "pages:index" %}">두번째 앱 메인 페이지</a>
{% endblock content %}

수업자료/django/02-template-urls/articles/templates/articles/search.html
{% extends "articles/base.html" %}

{% block content %}
  <h1>Fake Naver</h1>
  <form action="https://search.naver.com/search.naver" method="GET">
    <label for="message">검색어 : </label>
    <input type="text" id="message" name="query">
    <input type="submit">
  </form>
{% endblock content %}

수업자료/django/02-template-urls/articles/templates/articles/throw.html
{% extends "articles/base.html" %}

{% block content %}
  <h1>Throw</h1>
  {% comment %} <form action="http://127.0.0.1:8000/catch/" method="GET"> {% endcomment %}
  {% comment %} <form action="/catch/" method="GET"> {% endcomment %}
  <form action="{% url "articles:catch" %}" method="GET">
    <input type="text" name="message">
    <input type="submit">
  </form>
{% endblock content %}

수업자료/django/02-template-urls/pages/templates/pages/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>두번째 앱의 메인 페이지</h1>
</body>
</html>